# Generated by Django 3.1.1 on 2021-10-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('isapproved', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('package', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=200, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('withdrawal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('Total_earning', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
