# Generated by Django 3.1.1 on 2021-10-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhistory',
            name='_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
