# Generated by Django 3.1.1 on 2021-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0002_auto_20211022_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhistory',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
